/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TButton: typeof import('tdesign-vue-next')['Button']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    THeader: typeof import('tdesign-vue-next')['Header']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TOption: typeof import('tdesign-vue-next')['Option']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSkeleton: typeof import('tdesign-vue-next')['Skeleton']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTimeline: typeof import('tdesign-vue-next')['Timeline']
    TTimelineItem: typeof import('tdesign-vue-next')['TimelineItem']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    TTransfer: typeof import('tdesign-vue-next')['Transfer']
  }
}
